name: Create Linear Ticket on QA Label

on:
  pull_request:
    types: [labeled]

jobs:
  create-qa-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check label
        id: check-label
        if: ${{ github.event.label.name == 'ready for qa' }}
        env:
          LINEAR_API_TOKEN: ${{ secrets.LINEAR_API_KEY }}
        run: |
          curl -X POST https://api.linear.app/graphql \
          -H "Authorization: $LINEAR_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
          "query": "mutation { issueCreate(input: {teamId: \"5bc9b489-bb18-4637-b0e7-d20b931eb0db\", title: \"QA ticket for pull request #${{ github.event.pull_request.title }}\", description: \"Pull request URL: ${{ github.event.pull_request.html_url }}\"}) { issue { id } } }"
          }'
